services:
  # This is a one-off container just for setting the Babylon keys
  set-babylon-keys:
    container_name: set-babylon-keys
    image: snapchain/babylon-deployment-utils:fdceb0c
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.deploy/babylond:/home/.babylond
      - ${PWD}/.consumer-finality-provider:/home/.consumer-finality-provider
    entrypoint:
      - /bin/bash
      - -c
      - /set-babylon-keys.sh

  # This is a one-off container just for registering the consumer chain
  register-consumer-chain:
    container_name: register-consumer-chain
    image: snapchain/babylon-deployment-utils:fdceb0c
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.deploy/babylond:/home/.babylond
    entrypoint:
      - /bin/bash
      - -c
      - /register-consumer-chain.sh

  # This is a one-off container just for deploying cw contract
  deploy-cw-contract:
    container_name: deploy-cw-contract
    image: snapchain/babylon-deployment-utils:fdceb0c
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.deploy/babylond:/home/.babylond
      - ${PWD}/.deploy/contract:/home/.deploy
    entrypoint:
      - /bin/bash
      - -c
      - /deploy-cw-contract.sh

  # This is a one-off container just for setting the finality contract enabled value
  toggle-cw-killswitch:
    container_name: toggle-cw-killswitch
    image: snapchain/babylon-deployment-utils:fdceb0c
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.deploy/babylond:/home/.babylond
      - ${PWD}/.deploy/contract:/home/.deploy
    entrypoint:
      - /bin/bash
      - -c
      - /toggle-cw-killswitch.sh

  # This is a one-off container just for tearing down the Babylon integration
  teardown:
    container_name: teardown
    image: snapchain/babylon-deployment-utils:fdceb0c
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.deploy/babylond:/home/.babylond
      - ${PWD}/.consumer-finality-provider:/home/.consumer-finality-provider
    entrypoint:
      - /bin/bash
      - -c
      - /teardown.sh

  btc-staker:
    container_name: btc-staker
    # https://github.com/babylonlabs-io/btc-staker/commit/484bcb8fd9b7b0b525234d704dd049b1ef18e29f
    # euphrates-0.5.0-rc.0
    image: babylonlabs/btc-staker:484bcb8fd9b7b0b525234d704dd049b1ef18e29f
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.btc-staker:/home/btcstaker/.stakerd
    ports:
      - "15812:15812"
    restart: unless-stopped
    networks:
      - babylon-integration

  consumer-eotsmanager:
    container_name: consumer-eotsmanager
    # https://github.com/babylonlabs-io/finality-provider/pull/213
    image: baichuan3/finality-provider:latest
    command: eotsd start
    volumes:
      - ${PWD}/.consumer-eotsmanager:/home/finality-provider/.eotsd
    ports:
      - "15813:15813"
    restart: unless-stopped
    networks:
      - babylon-integration

  consumer-finality-provider:
    container_name: consumer-finality-provider
    # https://github.com/babylonlabs-io/finality-provider/pull/213
#    image: babylonlabs/finality-provider:8e8384a11d63e8841c28fe746fd01ff9b585e831
    image: baichuan3/finality-provider:latest
    command: fpd start
    volumes:
      - ${PWD}/.consumer-finality-provider:/home/finality-provider/.fpd
    ports:
      - "12581:12581"
    depends_on:
      - consumer-eotsmanager
    restart: unless-stopped
    networks:
      - babylon-integration

  finality-gadget:
    container_name: finality-gadget
    # https://github.com/babylonlabs-io/finality-gadget/commit/ac0ac994d987f202757a4646ccddb8c139b1b64d
    image: baichuan3/finality-gadget:latest
    command: >
      opfgd start --cfg /home/finality-gadget/roochfgd.toml
    ports:
      - "50051:50051"
      - "18080:8080"
    volumes:
      - ${PWD}/.finality-gadget:/home/finality-gadget
    restart: unless-stopped
    networks:
      - babylon-integration

  finality-explorer:
    container_name: finality-explorer
    image: snapchain/finality-explorer:sha-7dfdc59
    ports:
      - "13000:3000"
    env_file:
      - "${PWD}/.env.babylon-integration"
    restart: unless-stopped

  roochnode:
    image: baichuan3/rooch:latest
    container_name: roochnode
    env_file:
      - "${PWD}/.env.bitcoin"
      - "${PWD}/.env.rooch"
#    volumes:
#      - "rooch_data:/home/.rooch"
#    restart: always
    command: >
      babylond --home /babylondhome start --log_format 'plain' 2>&1 | tee /babylondhome/babylond.log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "6767:6767"
      - "9184:9184"
    networks:
      localnet:
        ipv4_address: 192.168.10.24
    volumes:
      - ../.testnets/rooch:/home/.rooch:Z
#    depends_on:
#      - babylondnode0
    restart: unless-stopped

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
